"""BCrypt password hashing — equivalent of Spring's BCryptPasswordEncoder.

Spring's BCryptPasswordEncoder produces hashes in the standard BCrypt format
($2a$10$...). passlib's bcrypt scheme is wire-format-compatible, so hashes
generated by the Java implementation verify correctly with this module and
vice versa. This cross-language compatibility is verified by test_auth.py's
BCrypt compatibility test (spec §19 checklist item 3).
"""
from passlib.context import CryptContext

_pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")


def hash_password(plain: str) -> str:
    """Hash a plaintext password using BCrypt. Equivalent of passwordEncoder.encode()."""
    return _pwd_context.hash(plain)


def verify_password(plain: str, hashed: str) -> bool:
    """Verify a plaintext password against a BCrypt hash. Equivalent of passwordEncoder.matches()."""
    return _pwd_context.verify(plain, hashed)
