/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        background: "#0E0801",
        surface: "#1C1108",
        "surface-dim": "#191206",
        "surface-bright": "#413828",
        "surface-variant": "#3D3324",
        "surface-container-lowest": "#140D03",
        "surface-container-low": "#221A0D",
        "surface-container": "#261E10",
        "surface-container-high": "#31291A",
        "surface-container-highest": "#3D3324",
        "surface-lowest": "#0E0801",
        "surface-tint": "#FFB596",
        "card-input": "#2A1A0A",
        primary: "#FFB596",
        "primary-container": "#FF6500",
        "primary-fixed": "#FFDBCD",
        "primary-fixed-dim": "#FFB596",
        "on-primary": "#581E00",
        "on-primary-container": "#551D00",
        "on-primary-fixed": "#360F00",
        "on-primary-fixed-variant": "#7D2D00",
        "inverse-primary": "#A33E00",
        secondary: "#E3C195",
        "secondary-container": "#5A4321",
        "secondary-fixed": "#FFDDB2",
        "secondary-fixed-dim": "#E3C195",
        "on-secondary": "#412C0D",
        "on-secondary-container": "#D0B085",
        "on-secondary-fixed": "#291800",
        "on-secondary-fixed-variant": "#5A4321",
        tertiary: "#9DCAFF",
        "tertiary-container": "#009BFE",
        "tertiary-fixed": "#D1E4FF",
        "tertiary-fixed-dim": "#9DCAFF",
        "on-tertiary": "#003257",
        "on-tertiary-container": "#003155",
        "on-tertiary-fixed": "#001D36",
        "on-tertiary-fixed-variant": "#00497C",
        "on-surface": "#F0E0CA",
        "on-surface-variant": "#E3BFB1",
        "on-background": "#F0E0CA",
        "inverse-surface": "#F0E0CA",
        "inverse-on-surface": "#382F20",
        "muted-text": "#7A6045",
        outline: "#AA8A7D",
        "outline-variant": "#5A4136",
        "border-glow": "rgba(255, 101, 0, 0.18)",
        "accent-rating": "#FFB347",
        error: "#FFB4AB",
        "error-container": "#93000A",
        "on-error": "#690005",
        "on-error-container": "#FFDAD6",
        success: "#22C55E",
        "success-dim": "rgba(34, 197, 94, 0.08)",
        brand: {
          bg:        "#0E0801",
          surface:   "#1C1108",
          card:      "#2A1A0A",
          primary:   "#FF6500",
          primaryhv: "#CC5200",
          accent:    "#FFB347",
          text1:     "#FFFFFF",
          text2:     "#C8A87E",
          text3:     "#7A6045",
          border:    "rgba(255,101,0,0.18)",
          glass:     "rgba(255,255,255,0.06)",
          success:   "#22C55E",
          warning:   "#F59E0B",
          error:     "#EF4444",
        }
      },
      fontFamily: {
        poppins: ["Poppins", "sans-serif"],
        "be-vietnam": ["Be Vietnam Pro", "sans-serif"],
        "headline-lg": ["Be Vietnam Pro", "sans-serif"],
        "headline-md": ["Be Vietnam Pro", "sans-serif"],
        "body-lg": ["Be Vietnam Pro", "sans-serif"],
        "body-md": ["Be Vietnam Pro", "sans-serif"],
        "label-md": ["Be Vietnam Pro", "sans-serif"],
        "label-sm": ["Be Vietnam Pro", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-lg": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-md-mobile": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "500" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "14px", fontWeight: "400" }],
      },
      spacing: {
        base: "4px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "24px",
        "gutter-grid": "12px",
        "margin-mobile": "20px",
        safe: "max(8px, env(safe-area-inset-bottom))",
      },
      borderRadius: {
        "2xl": "16px",
        "3xl": "24px",
        "4xl": "32px",
      },
      boxShadow: {
        card:   "0 4px 24px rgba(0,0,0,0.4)",
        orange: "0 4px 20px rgba(255,101,0,0.35)",
        glass:  "0 8px 32px rgba(0,0,0,0.3)",
      },
    },
  },
  plugins: [],
};
